server:
  port: 8300
spring:
  application:
    name: micro-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8000/micro-security/security/check
      #prefer-token-info: false



logging:
  level:
    org.springframework.security: debug

