server:
  port: 8700
  servlet:
    context-path: /client1
  #这里也可以设置session的名称和sso-server区分
#  servlet:
#    session:
#      cookie:
#        name: OAUTH2SESSION
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: micro-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8500/sso/oauth/token_key
      prefer-token-info: false
    client:
      client-id: pc
      client-secret: 123456
      access-token-uri: http://localhost:8500/sso/oauth/token
      user-authorization-uri: http://localhost:8500/sso/oauth/authorize




logging:
  level:
    org.springframework.security: debug

