server:
  port: 9500

spring:
  application:
    name: micro-security
  redis:
    host: 120.78.160.86
    port: 6379
    lettuce:
      pool:
        max-active: 15
        min-idle: 0
        max-idle: 8
        max-wait: 3000
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848





logging:
  level:
    org.springframework.security: debug