server:
  port: 8701
#  servlet:
#    context-path: /client2
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION2
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: micro-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8500/oauth/token_key
      prefer-token-info: false
    client:
      client-id: pc2
      client-secret: 123456
      access-token-uri: http://localhost:8500/oauth/token
      user-authorization-uri: http://localhost:8500/oauth/authorize




logging:
  level:
    org.springframework.security: debug

