server:
  port: 8500
  servlet:
    #同一台机器都用localhost,这个一定要配,否则cookie混淆,用域名可以不配
    context-path: /sso

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sso-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.160.86:3306/security?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848




logging:
  level:
    root: info
    org.springframework.security: debug
    com.bryan.cloud.dao: debug



